version: '3.7'

services:
 
  powercenter:
    image: koda_powercenter
    container_name: powercenter
    environment:
      POWERCENTER_UDP_PORT: 50000
      POWERCENTER_TCP_PORT: 80
    restart: unless-stopped
    ports:
      - 80:80
      - 50000:50000/udp
    networks:
      powernetwork:
        ipv4_address: 172.20.0.60

  windplant:
    image: koda_participant
    container_name: windplant
    environment:
      participantMode: Producer
      participantID: 1
      participantDesIP: 172.20.0.60
      participantDesPort: 50000
    networks:
      powernetwork:
    depends_on:
    - powercenter

  nuclearplant:
    image: koda_participant
    container_name: nuclearplant
    environment:
      participantMode: Producer
      participantID: 2
      participantDesIP: 172.20.0.60
      participantDesPort: 50000
    networks:
      powernetwork:
    depends_on:
    - powercenter

  solarplant:
    image: koda_participant
    container_name: solarplant
    environment:
      participantMode: Producer
      participantID: 3
      participantDesIP: 172.20.0.60
      participantDesPort: 50000
    networks:
      powernetwork:
    depends_on:
    - powercenter

  farm:
    image: koda_participant
    container_name: farm
    environment:
      participantMode: Consumer
      participantID: 4
      participantDesIP: 172.20.0.60
      participantDesPort: 50000
    networks:
      powernetwork:
    depends_on:
    - powercenter
 
networks:
  powernetwork:
    external: true




  
