version: '3.7'

services:

  powercenter:
    image: koda_powercenter
    container_name: powercenter
    environment:
      POWERCENTER_RPC_PORT: 50001
      POWERCENTER_UDP_PORT: 50000
      POWERCENTER_TCP_PORT: 80
      POWERCENTER_MQTT_ID: Center_1
      POWERCENTER_MQTT_HOST: koda_broker
      POWERCENTER_MQTT_PORT: 1883
      POWERCENTER_MQTT_TIMEOUT: 60
    restart: unless-stopped
    ports:
      - 80:80
      - 50000:50000/udp
      - 50001:50001
    networks:
      powernetwork:
        ipv4_address: 172.20.0.60
    depends_on:
    - mosquitto

  external:
    image: koda_external
    container_name: external
    environment:
      REQUEST_TARGET_IP: 172.20.0.60
      REQUEST_TARGET_PORT: 50001
      RESPONSE_PAGE_SIZE: 10000
    networks:
      powernetwork:
    depends_on:
    - powercenter
    - windplant
    - nuclearplant
    - solarplant
    - farm
    - city_large

  mosquitto:
    image: koda_mqtt
    container_name: koda_broker
    ports:
      - "1883:1883"
    networks:
      powernetwork:

  windplant:
    image: koda_participant
    container_name: windplant
    environment:
      PARTICIPANT_MODE: Producer
      PARTICIPANT_ID: 1
      PARTICIPANT_DES_IP: 172.20.0.60
      PARTICIPANT_DES_PORT: 50000
      PARTICIPANT_RPC_PORT: 50001
      PARTICIPANT_SLEEP_DURATION: 20
      PARTICIPANT_USE_UDP: 1
      PARTICIPANT_USE_MQTT: 1
      PARTICIPANT_KW_MAX: 500
      PARTICIPANT_KW_MIN: 10
      PARTICIPANT_KW_FLUCT: 0.1
      MQTT_ID: Participant_1
      MQTT_HOST: koda_broker
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
    networks:
      powernetwork:
        ipv4_address: 172.20.0.10
    depends_on:
    - powercenter

  nuclearplant:
    image: koda_participant
    container_name: nuclearplant
    environment:
      PARTICIPANT_MODE: Producer
      PARTICIPANT_ID: 2
      PARTICIPANT_DES_IP: 172.20.0.60
      PARTICIPANT_DES_PORT: 50000
      PARTICIPANT_RPC_PORT: 50001
      PARTICIPANT_SLEEP_DURATION: 25
      PARTICIPANT_USE_MQTT: 1
      PARTICIPANT_KW_MAX: 50000
      PARTICIPANT_KW_MIN: 1000
      PARTICIPANT_KW_FLUCT: 0.001
      MQTT_ID: Participant_2
      MQTT_HOST: koda_broker
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
    networks:
      powernetwork:
        ipv4_address: 172.20.0.20
    depends_on:
    - powercenter

  solarplant:
    image: koda_participant
    container_name: solarplant
    environment:
      PARTICIPANT_MODE: Producer
      PARTICIPANT_ID: 3
      PARTICIPANT_DES_IP: 172.20.0.60
      PARTICIPANT_DES_PORT: 50000
      PARTICIPANT_RPC_PORT: 50001
      PARTICIPANT_SLEEP_DURATION: 25
      PARTICIPANT_USE_MQTT: 1
      PARTICIPANT_KW_MAX: 2000
      PARTICIPANT_KW_MIN: 5
      PARTICIPANT_KW_FLUCT: 0.2
      MQTT_ID: Participant_3
      MQTT_HOST: koda_broker
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
    networks:
      powernetwork:
        ipv4_address: 172.20.0.30
    depends_on:
    - powercenter

  farm:
    image: koda_participant
    container_name: farm
    environment:
      PARTICIPANT_MODE: Consumer
      PARTICIPANT_ID: 4
      PARTICIPANT_DES_IP: 172.20.0.60
      PARTICIPANT_DES_PORT: 50000
      PARTICIPANT_RPC_PORT: 50001
      PARTICIPANT_SLEEP_DURATION: 25
      PARTICIPANT_USE_UDP: 1
      PARTICIPANT_KW_MAX: 100
      PARTICIPANT_KW_MIN: 10
      PARTICIPANT_KW_FLUCT: 0.5
      MQTT_ID: Participant_4
      MQTT_HOST: koda_broker
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
    networks:
      powernetwork:
        ipv4_address: 172.20.0.40
    depends_on:
    - powercenter
 
  city_large:
    image: koda_participant
    container_name: frankburg
    environment:
      PARTICIPANT_MODE: Consumer
      PARTICIPANT_ID: 5
      PARTICIPANT_DES_IP: 172.20.0.60
      PARTICIPANT_DES_PORT: 50000
      PARTICIPANT_RPC_PORT: 50001
      PARTICIPANT_SLEEP_DURATION: 25
      PARTICIPANT_USE_MQTT: 1
      PARTICIPANT_KW_MAX: 900000
      PARTICIPANT_KW_MIN: 1000
      PARTICIPANT_KW_FLUCT: 0.75
      MQTT_ID: Participant_5
      MQTT_HOST: koda_broker
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
    networks:
      powernetwork:
        ipv4_address: 172.20.0.50
    depends_on:
    - powercenter
networks:
  powernetwork:
    external: true




  
